### PR TITLE
Attempt to make CARMA kernel jit-compliant

### PR DESCRIPTION
**Pull request by dhuppenkothen**
I'm currently trying to get the CARMA model working with JaxNS, and am running into jit-compiler issues that I've tracked down to the different behaviour between `jax.numpy.roots` and `numpy.roots`, and the use of the numpy `roll` function.

These seem like small fixes, but I won't pretend I really understand either JAX jit or tinygp in enough detail to know whether it breaks anything.

Looking at the issues (which I guess I should have done before), it looks like I'm not the first person to find this error (cf #89), but I don't know if #90 will solve this issue (or what the current status of this PR is?)

### CODE REVIEW

**Comment by dfm** [comment]
Thanks! I think #90 won't have this issue, and I'd love to get that working whenever @ywx649999311 gets a chance to revisit it! However, I'm happy to merge this in the meantime as a band-aid fix.

**Comment by dfm** [comment]
In the meantime, @dhuppenkothen can you:

1. Add a file called `news/188.bugfix` that describes this fix in a single line. See [the changelog](https://tinygp.readthedocs.io/en/stable/news.html) for examples - each bullet point was generated from one of these files.
2. Add your info to `.zenodo.json` so that you'll be included as an author on the next release.

Thanks!

**Comment by ywx649999311** [comment]
> Thanks! I think #90 won't have this issue, and I'd love to get that working whenever @ywx649999311 gets a chance to revisit it! However, I'm happy to merge this in the meantime as a band-aid fix.

Hi @dfm, I am currently in the middle of moving between countries for my new job. I will make this the number one priority once I settle down, but it won't be until the 23rd. I am sorry for the long delay.

**Comment by dfm** [comment]
Absolutely no stress, @ywx649999311!! Looking forward to checking back in whenever you're ready!

**Pull request merged**
